name             'mysql_master'
maintainer       'Greg Lane'
maintainer_email 'glane@gannett.com'
license          'All rights reserved'
description      'Installs/Configures mysql_master'
long_description 'Installs/Configures mysql_master'
version          '0.1.0'

depends 'mysql'
depends 'lvm'
depends 'selinux'
depends 'sysctl'
depends 'limits'
depends 'iptables'
depends 'mysql_config'
depends 'gdp-base-linux'
depends 'mysql2_chef_gem'
depends 'database'
